enableColors: true

httpProxy: "http://127.0.0.1:7890"

httpsProxy: "https://127.0.0.1:7890"

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
